# Generated by Django 2.2.10 on 2020-03-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200320_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mode',
            new_name='post_mode',
        ),
    ]
